authors:
  Haotian:
    name: Haotian
    description: Developer
    avatar: https://cdn.jsdelivr.net/gh/alohe/avatars/png/notion_10.png
    url: https://haotianfang.com/
  team:
    name: Team
    description: Team
    avatar: https://cdn.jsdelivr.net/gh/alohe/avatars/png/notion_11.png
    url: https://haotianfang.com/